apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "krakend.fullname" . }}
  labels:
    {{- include "krakend.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "krakend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "krakend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "krakend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.addlVolumeMounts }}
          volumeMounts:
            - name: config
              mountPath: /etc/krakend/
            {{- toYaml .Values.addlVolumeMounts | nindent 12 }}
            {{- if .Values.plugin.enabled}}
            - name: volume-plugin
              mountPath: /etc/krakend/plugin/
            {{- end }}
          {{- end }}
          {{- if .Values.commands.enabled }}
          command: {{.Values.commands.command}}
          args: {{ .Values.commands.args}}
          {{- end }}
          env:
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.path}}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.path}}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.plugin.enabled}}
        - name: alpine
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: alpine
          imagePullPolicy: IfNotPresent
          name: myvolumes-container-1
          volumeMounts:
            - mountPath: /download
              name: volume-plugin
          command: ['sh','-c','{{ .Values.plugin.command }}']
      {{- end}}
      volumes:
        - name: config
          configMap:
            name: config-krakend-json
        {{- if .Values.addlVolumes }}
        {{- toYaml .Values.addlVolumes | nindent 8 }}
        {{- end }}
        {{- if .Values.plugin.enabled}}
        - name: volume-plugin
          emptyDir: {}
        {{- end }}
      {{- if .Values.initContainers}}
      initContainers:
      {{- end }}  
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
